import { LitElement, TemplateResult } from 'lit';
import { OscdFilledButton } from '@omicronenergy/oscd-ui/button/OscdFilledButton.js';
import { OscdDialog } from '@omicronenergy/oscd-ui/dialog/OscdDialog.js';
import { OscdIcon } from '@omicronenergy/oscd-ui/icon/OscdIcon.js';
import { OscdIconButton } from '@omicronenergy/oscd-ui/iconbutton/OscdIconButton.js';
import { OscdOutlinedButton } from '@omicronenergy/oscd-ui/button/OscdOutlinedButton.js';
import { OscdTextButton } from '@omicronenergy/oscd-ui/button/OscdTextButton.js';
import { OscdTreeGrid } from '@omicronenergy/oscd-ui/tree-grid/OscdTreeGrid.js';
import { DataSetElementEditor } from '../dataset/data-set-element-editor.js';
import { ReportControlElementEditor } from './report-control-element-editor.js';
import { OscdOutlinedIconButton } from '@omicronenergy/oscd-ui/iconbutton/OscdOutlinedIconButton.js';
declare const ClientLnAssignmentDialog_base: typeof LitElement & import("@open-wc/scoped-elements/lit-element.js").ScopedElementsHostConstructor;
export declare class ClientLnAssignmentDialog extends ClientLnAssignmentDialog_base {
    static scopedElements: {
        'oscd-outlined-button': typeof OscdOutlinedButton;
        'oscd-text-button': typeof OscdTextButton;
        'oscd-filled-button': typeof OscdFilledButton;
        'oscd-icon-button': typeof OscdIconButton;
        'oscd-icon': typeof OscdIcon;
        'oscd-dialog': typeof OscdDialog;
        'oscd-tree-grid': typeof OscdTreeGrid;
        'oscd-outlined-icon-button': typeof OscdOutlinedIconButton;
    };
    doc: XMLDocument;
    private clientLnAssignmentReport?;
    private selectedClientLnIds;
    private initialClientLnIds;
    private clientLnTreePaths;
    private showSelectedClientLnsOnly;
    selectionList: HTMLElement;
    clientLnAssignmentDialog: OscdDialog;
    private clientLnTreeGrid?;
    selectReportControlButton: OscdOutlinedButton;
    rpControlElementEditor: ReportControlElementEditor;
    dataSetElementEditor: DataSetElementEditor;
    private get allClientLogicalNodes();
    open(reportControl: Element): Promise<void>;
    private clientLnId;
    private isValidClientLogicalNode;
    private clientLnTreePath;
    private clientLnTreePathForId;
    private clientLnIdForTreePath;
    private hasClientLn;
    private clientLnForLogicalNode;
    private assignedClientLogicalNodes;
    private clientLogicalNodesForReport;
    private setTreeNode;
    private clientLnTreeData;
    private clientLnInsert;
    private updateSelectedClientLns;
    private handleClientLnTreeClick;
    render(): TemplateResult;
    private logicalNodeName;
    static styles: import("lit").CSSResult;
}
export {};
