import { LitElement, TemplateResult } from 'lit';
import { OscdFilledButton } from '@omicronenergy/oscd-ui/button/OscdFilledButton.js';
import { OscdDialog } from '@omicronenergy/oscd-ui/dialog/OscdDialog.js';
import { OscdIcon } from '@omicronenergy/oscd-ui/icon/OscdIcon.js';
import { OscdOutlinedIconButton } from '@omicronenergy/oscd-ui/iconbutton/OscdOutlinedIconButton.js';
import { OscdOutlinedTextField } from '@omicronenergy/oscd-ui/textfield/OscdOutlinedTextField.js';
import { OscdTextButton } from '@omicronenergy/oscd-ui/button/OscdTextButton.js';
import { OscdTree } from '@omicronenergy/oscd-ui/tree/OscdTree.js';
import { OscdTreeItem } from '@omicronenergy/oscd-ui/tree/OscdTreeItem.js';
declare const ClientLnAssignmentDialog_base: typeof LitElement & import("@open-wc/scoped-elements/lit-element.js").ScopedElementsHostConstructor;
export declare class ClientLnAssignmentDialog extends ClientLnAssignmentDialog_base {
    static scopedElements: {
        'oscd-text-button': typeof OscdTextButton;
        'oscd-filled-button': typeof OscdFilledButton;
        'oscd-icon': typeof OscdIcon;
        'oscd-dialog': typeof OscdDialog;
        'oscd-outlined-text-field': typeof OscdOutlinedTextField;
        'oscd-outlined-icon-button': typeof OscdOutlinedIconButton;
        'oscd-tree': typeof OscdTree;
        'oscd-tree-item': typeof OscdTreeItem;
    };
    doc: XMLDocument;
    private clientLnAssignmentReport?;
    private selectedClientLnIds;
    private initialClientLnIds;
    private expandedClientLnNodeIds;
    private clientLnFilter;
    private showSelectedClientLnsOnly;
    clientLnAssignmentDialog: OscdDialog;
    private clientLnTree?;
    private get allClientLogicalNodes();
    open(reportControl: Element): Promise<void>;
    private clientLnId;
    private isValidClientLogicalNode;
    private clientLnTreePath;
    private clientLnTreePathForId;
    private hasClientLn;
    private clientLnForLogicalNode;
    private assignedClientLogicalNodes;
    private clientLogicalNodesForReport;
    private getOrCreateTreeNode;
    private matchesClientLnFilter;
    private clientLnTreeData;
    private clientLnInsert;
    private updateSelectedClientLns;
    private expandedNodeIdsForClientLnIds;
    private clientLnPathLabel;
    private maxClientLimit;
    private isClientLnSelectable;
    private isClientLnDisabled;
    private handleSelectedClientLnIdsChanged;
    private renderClientLnTreeItem;
    private clientLnNodeIcon;
    render(): TemplateResult;
    private logicalNodeName;
    static styles: import("lit").CSSResult;
}
export {};
