import { TemplateResult } from 'lit';
import { OscdActionList } from '@omicronenergy/oscd-ui/action-list/OscdActionList.js';
import { OscdFilledButton } from '@omicronenergy/oscd-ui/button/OscdFilledButton.js';
import { OscdDialog } from '@omicronenergy/oscd-ui/dialog/OscdDialog.js';
import { OscdIcon } from '@omicronenergy/oscd-ui/icon/OscdIcon.js';
import { OscdIconButton } from '@omicronenergy/oscd-ui/iconbutton/OscdIconButton.js';
import { OscdList } from '@omicronenergy/oscd-ui/list/OscdList.js';
import { OscdListItem } from '@omicronenergy/oscd-ui/list/OscdListItem.js';
import { OscdMenu } from '@omicronenergy/oscd-ui/menu/OscdMenu.js';
import { OscdMenuItem } from '@omicronenergy/oscd-ui/menu/OscdMenuItem.js';
import { OscdOutlinedButton } from '@omicronenergy/oscd-ui/button/OscdOutlinedButton.js';
import { OscdOutlinedTextField } from '@omicronenergy/oscd-ui/textfield/OscdOutlinedTextField.js';
import { OscdTextButton } from '@omicronenergy/oscd-ui/button/OscdTextButton.js';
import { DataSetElementEditor } from '../dataset/data-set-element-editor.js';
import { ReportControlElementEditor } from './report-control-element-editor.js';
import { BaseElementEditor } from '../base-element-editor.js';
import { ClientLnAssignmentDialog } from './client-ln-assignment-dialog.js';
export declare class ReportControlEditor extends BaseElementEditor {
    static scopedElements: {
        'oscd-action-list': typeof OscdActionList;
        'data-set-element-editor': typeof DataSetElementEditor;
        'oscd-list': typeof OscdList;
        'oscd-list-item': typeof OscdListItem;
        'oscd-menu': typeof OscdMenu;
        'oscd-menu-item': typeof OscdMenuItem;
        'oscd-outlined-button': typeof OscdOutlinedButton;
        'oscd-outlined-text-field': typeof OscdOutlinedTextField;
        'oscd-text-button': typeof OscdTextButton;
        'oscd-filled-button': typeof OscdFilledButton;
        'report-control-element-editor': typeof ReportControlElementEditor;
        'oscd-icon-button': typeof OscdIconButton;
        'oscd-icon': typeof OscdIcon;
        'oscd-dialog': typeof OscdDialog;
        'clientln-assignment-dialog': typeof ClientLnAssignmentDialog;
    };
    private reportFilter;
    selectionList: HTMLElement;
    clientLnAssignmentDialog: ClientLnAssignmentDialog;
    selectReportControlButton: OscdOutlinedButton;
    rpControlElementEditor: ReportControlElementEditor;
    dataSetElementEditor: DataSetElementEditor;
    private renderElementEditorContainer;
    private createReportControl;
    private canCreateReportControl;
    private selectReportControl;
    private removeReportControl;
    private openClientLnAssignmentDialog;
    private showReportActionsMenu;
    private matchesReportFilter;
    private renderReportListItem;
    private renderSelectionList;
    private renderToggleButton;
    render(): TemplateResult;
    static styles: import("lit").CSSResult;
}
